### ISSUE TITLE
Missing required field

### ISSUE THREAD

**Issue by 2press** [KirillMysnik/obs-ws-rc#1]
I am getting a lot of error messages of this kind:

```OBS-WS-RC: 'TransitionBegin' event instantiation raised (invalid protocol.json?)
Traceback (most recent call last):
  File "c:\users\tasch\appdata\local\programs\python\python35-32\lib\site-packages\obswsrc\client.py", line 363, in _handle_event
    event = event_class(data)
  File "c:\users\tasch\appdata\local\programs\python\python35-32\lib\site-packages\obswsrc\struct.py", line 95, in __init__
    field_name=field.field_name))
TypeError: Struct 'TransitionBeginEvent': Missing required name field

The callbacks are not going to be called!
OBS-WS-RC: 'SwitchScenes' event instantiation raised (invalid protocol.json?)
Traceback (most recent call last):
  File "c:\users\tasch\appdata\local\programs\python\python35-32\lib\site-packages\obswsrc\client.py", line 363, in _handle_event
    event = event_class(data)
  File "c:\users\tasch\appdata\local\programs\python\python35-32\lib\site-packages\obswsrc\struct.py", line 95, in __init__
    field_name=field.field_name))
TypeError: Struct 'SwitchScenesEvent': Missing required sources field
```

**Comment by KirillMysnik** [comment]
Try this way of importing:
```python
import obswsrc
obswsrc.struct.SKIP_OPTIONAL_CHECK = True
```
Most probably, the reason for this issue is the protocol.json not representing the real protocol. I've seen lots of mistakes in OBS-WebSocket plugin protocol description. Most "popular" mistake is that they forget to declare a field as optional.

`obs-ws-rc` will raise errors if the field which is not marked as optional (according to OBS-WS protocol page) is missing in the OBS response. This is probably your case. Setting `SKIP_OPTIONAL_CHECK` flag will make the package to ignore such missing fields.
